import api from "./api";

/**
 * Cloudinary signed upload utility.
 *
 * Uploads a file from the browser to Cloudinary securely using a signature
 * generated by our backend.
 */

export interface UploadResult {
  url: string;
  content_type: string;
  size: number;
}

interface SignatureResponse {
  signature: string;
  timestamp: number;
  cloudName: string;
  apiKey: string;
  folder: string;
  context: string;
}

/**
 * Fetch a secure upload signature from the backend.
 */
async function getSignature(): Promise<SignatureResponse> {
  const res = await api.get<SignatureResponse>("/upload/signature");
  return res.data;
}

/**
 * Upload a single file to Cloudinary securely using a backend signature.
 *
 * @param file  The File object to upload.
 * @param onProgress  Optional callback receiving 0–100.
 * @returns  `{ url, content_type, size }` matching the backend Media schema.
 */
export async function uploadToCloudinary(
  file: File,
  onProgress?: (percent: number) => void,
): Promise<UploadResult> {
  // 1. Get permission slip
  const sig = await getSignature();

  // 2. Build the payload
  const formData = new FormData();
  formData.append("file", file);
  formData.append("api_key", sig.apiKey);
  formData.append("timestamp", String(sig.timestamp));
  formData.append("signature", sig.signature);
  formData.append("folder", sig.folder);
  if (sig.context) formData.append("context", sig.context);

  // 3. Upload directly to Cloudinary
  return new Promise<UploadResult>((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open(
      "POST",
      `https://api.cloudinary.com/v1_1/${sig.cloudName}/auto/upload`,
    );

    xhr.upload.onprogress = (e) => {
      if (e.lengthComputable && onProgress) {
        onProgress(Math.round((e.loaded / e.total) * 100));
      }
    };

    xhr.onload = () => {
      if (xhr.status >= 200 && xhr.status < 300) {
        const data = JSON.parse(xhr.responseText);
        resolve({
          url: data.secure_url,
          content_type: data.resource_type + "/" + data.format, // e.g. "image/jpeg"
          size: data.bytes,
        });
      } else {
        reject(new Error(`Upload failed: ${xhr.statusText}`));
      }
    };

    xhr.onerror = () => reject(new Error("Network error during upload"));
    xhr.send(formData);
  });
}

/**
 * Upload multiple files in parallel, aggregating per-file progress into
 * an overall 0–100 value.
 */
export async function uploadMultipleToCloudinary(
  files: File[],
  onOverallProgress?: (percent: number) => void,
): Promise<UploadResult[]> {
  const progresses = new Array(files.length).fill(0);

  const report = () => {
    if (!onOverallProgress) return;
    const total = progresses.reduce((a, b) => a + b, 0);
    onOverallProgress(Math.round(total / files.length));
  };

  const promises = files.map((file, i) =>
    uploadToCloudinary(file, (p) => {
      progresses[i] = p;
      report();
    }),
  );

  return Promise.all(promises);
}
